# first stage which is build
FROM node:latest AS builder

WORKDIR /app

COPY  package*.json ./

RUN npm install

COPY . .

RUN npm run build

#second stage which is run using distorless image taken from github node.js(lastest)
FROM gcr.io/distroless/nodejs:latest

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5173

CMD [ "node","dist/index.js" ]